import Link from "next/link";

const examples = [
  {
    name: "ShipLog",
    description: "Automated changelog generator using MiMo to analyze git history",
    model: "Xiaomi MiMo-2.5-Pro",
    target: "Xiaomi Model Credit Program",
    status: "Approved",
  },
  {
    name: "ClauseGuard",
    description: "Contract risk scanner that flags red clauses in plain English",
    model: "Xiaomi MiMo-2.5-Pro",
    target: "AI Grant Program",
    status: "Submitted",
  },
  {
    name: "BugLens",
    description: "Error log analyzer with root cause detection and fix suggestions",
    model: "Xiaomi MiMo-2.5-Pro",
    target: "Developer Tools Fund",
    status: "Approved",
  },
];

export default function Examples() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold mb-2">Example Pitches</h1>
      <p className="text-gray-600 mb-8">
        Real proposals generated by PitchForge. Use these as templates for your own submissions.
      </p>

      <div className="space-y-4">
        {examples.map((ex, i) => (
          <div key={i} className="card-hover p-6 rounded-xl border border-gray-100">
            <div className="flex items-start justify-between">
              <div>
                <h3 className="font-semibold text-lg">{ex.name}</h3>
                <p className="text-gray-600 text-sm mt-1">{ex.description}</p>
                <div className="flex gap-4 mt-3 text-xs text-gray-500">
                  <span>Model: {ex.model}</span>
                  <span>Target: {ex.target}</span>
                </div>
              </div>
              <span className={`text-xs px-2 py-1 rounded-full ${
                ex.status === "Approved" 
                  ? "bg-green-50 text-green-700" 
                  : "bg-yellow-50 text-yellow-700"
              }`}>
                {ex.status}
              </span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-12 text-center">
        <Link href="/builder" className="px-6 py-3 bg-brand-600 text-white rounded-lg font-medium hover:bg-brand-700 transition-colors">
          Build Your Own Pitch
        </Link>
      </div>
    </div>
  );
}
