export interface ProjectInput {
  name: string;
  problem: string;
  solution: string;
  users: string;
  techStack: string;
  modelUsed: string;
  repoUrl: string;
  demoUrl: string;
  evidence: EvidenceItem[];
  grantTarget: string;
}

export interface EvidenceItem {
  type: "repo" | "demo" | "screenshot" | "log" | "artifact" | "other";
  url: string;
  description: string;
}

export function generatePitch(input: ProjectInput): string {
  const evidenceSection = input.evidence
    .map((e, i) => `${i + 1}. **[${e.type.toUpperCase()}]** ${e.description}\n   ${e.url}`)
    .join("\n");

  return `# ${input.name}

## Summary

**${input.name}** solves a real problem: ${input.problem}

The solution: ${input.solution}

Built for: ${input.users}

---

## Technical Implementation

- **Stack:** ${input.techStack}
- **AI Model:** ${input.modelUsed}
- **Repository:** ${input.repoUrl}
- **Live Demo:** ${input.demoUrl}

---

## Why This Matters

${input.problem}

Existing solutions either don't exist or require significant manual effort. ${input.name} automates this through ${input.modelUsed}, reducing what used to take hours into minutes.

---

## Evidence of Work

${evidenceSection}

---

## Target Program

This proposal is submitted for: **${input.grantTarget}**

### What we're asking for

Access to ${input.modelUsed} will allow us to:
1. Scale the core functionality beyond local testing
2. Serve real users without rate-limit constraints
3. Iterate on prompt quality with production-level inference

### What we've already proven

- Working prototype deployed and publicly accessible
- Real user flow from input to generated output
- Clean codebase with documented architecture
- Evidence trail showing genuine AI-assisted development

---

## Credibility Signals

| Signal | Status |
|--------|--------|
| Public repository | ✓ ${input.repoUrl} |
| Live deployment | ✓ ${input.demoUrl} |
| Working AI integration | ✓ ${input.modelUsed} |
| Clear user persona | ✓ ${input.users} |
| Evidence artifacts | ✓ ${input.evidence.length} items |

---

*Generated by PitchForge — turning rough ideas into reviewer-ready proposals.*
`;
}

export function generateGrantAnswer(input: ProjectInput, maxLength: number = 2000): string {
  const answer = `${input.name} addresses ${input.problem} by providing ${input.solution}.

Our target users are ${input.users}. The project is built with ${input.techStack} and integrates ${input.modelUsed} for intelligent processing.

We have a working prototype deployed at ${input.demoUrl} with source code publicly available at ${input.repoUrl}. The implementation demonstrates real AI-assisted workflow with ${input.evidence.length} verifiable evidence artifacts.

We are applying to ${input.grantTarget} because access to ${input.modelUsed} will allow us to scale beyond local testing, serve real users, and iterate on output quality with production-grade inference.

What sets this apart: the project is not a concept — it is shipped, deployed, and publicly verifiable. Every claim maps to inspectable evidence.`;

  return answer.slice(0, maxLength);
}
